# UAT CONFIGURATIONS

# memcache configurations
locator.hibernate.cache.use_query_cache=false
locator.hibernate.cache.use_second_level_cache=false

# hibernate settings
locator.hibernate.memcached.servers=localhost:11211
locator.hibernate.dialect=org.hibernate.dialect.HSQLDialect
locator.hibernate.cache.provider_class=com.googlecode.hibernate.memcached.MemcachedCacheProvider

# debug settings
locator.hibernate.show_sql=true
locator.hibernate.format_sql=true
locator.hibernate.hbm2ddl.auto=true

# session settings
locator.hibernate.current_session_context_class=thread
locator.hibernate.transaction.factory_class=org.hibernate.transaction.JDBCTransactionFactory

# datasource settings
locator.c3po.jdbc.driver=com.mysql.jdbc.Driver
locator.c3po.jdbc.url=jdbc:mysql://mysql-master0.dba.wit.lockerz.int:3306/locator
locator.c3po.jdbc.user=awsuser
locator.c3po.jdbc.password=8RUwdO4Khk3HIF
locator.c3po.jdbc.acquireIncrement=1
locator.c3po.jdbc.initialPoolSize=5
locator.c3po.jdbc.maxPoolSize=5
locator.c3po.jdbc.minPoolSize=5
locator.c3po.jdbc.maxIdleTime=30

# memcache configurations
pod1.hibernate.cache.use_query_cache=false
pod1.hibernate.cache.use_second_level_cache=false

# hibernate settings
pod1.hibernate.memcached.servers=localhost:11211
pod1.hibernate.dialect=org.hibernate.dialect.HSQLDialect
pod1.hibernate.cache.provider_class=com.googlecode.hibernate.memcached.MemcachedCacheProvider

# debug settings
pod1.hibernate.show_sql=true
pod1.hibernate.format_sql=true
pod1.hibernate.hbm2ddl.auto=true

# session settings
pod1.hibernate.current_session_context_class=thread
pod1.hibernate.transaction.factory_class=org.hibernate.transaction.JDBCTransactionFactory

# datasource settings
pod1.c3po.jdbc.driver=com.mysql.jdbc.Driver
pod1.c3po.jdbc.url=jdbc:mysql://mysql-master0.dba.wit.lockerz.int:3306/pod1
pod1.c3po.jdbc.user=awsuser
pod1.c3po.jdbc.password=8RUwdO4Khk3HIF
pod1.c3po.jdbc.acquireIncrement=1
pod1.c3po.jdbc.initialPoolSize=5
pod1.c3po.jdbc.maxPoolSize=5
pod1.c3po.jdbc.minPoolSize=5
pod1.c3po.jdbc.maxIdleTime=30

# lockerz authentications
authorizer.apiKey=A1234567890B

# authenticate endpoint
authenticate.endpoint=http://argo0.phoenix.wit.lockerz.us:8080/user-1.0-SNAPSHOT/user/login/?apiKey={apiKey}&username={username}&password={password}&remoteIp={remoteIp}